export const ERRORMESSAGE = {
  'server.error': '服务器错误',
  'paging.bestselling.goods.fail': '分页获取滞销信息失败',
  'paging.brand.failx': '分页获取品牌失败',
  'list.brand.fail': '获取品牌列表失败',
  'paging.customer.profile.fail': '分页获取客户档案关系失败',
  'paging.customer.fail': '分页获取经销商失败',
  'list.dealer.indicator.fail': '获取经销商画像失败',
  'list.department.fail': '获取部门失败',
  'list.goods.group.fail': '获取产品组失败',
  'paging.goods.fail': '分页获取商品数据失败',
  'list.goods.series.fail': '获取产品系列失败',
  'paging.purchase.detail.fail': '分页获取进货明细失败',
  'paging.pss.summary.dealer.goods.fail': '获取进销存汇总失败',
  'paging.purchase.summary.dealer.goods.fail': '获取进货汇总失败',
  'paging.purchase.summary.dealer.fail': '获取进货汇总失败',
  'paging.sale.detail.fail': '分页获取销售明细失败',
  'paging.sale.summary.dealer.goods.fail': '分页获取销售汇总失败',
  'paging.sale.summary.dealer.fail': '分页获取销售汇总失败',
  'paging.stock.detail.fail': '分页获取库存明细失败',
  'paging.stock.summary.dealer.goods.fail': '分页获取库存汇总失败',
  'paging.stock.summary.dealer.fail': '分页获取库汇总失败',
  'paging.unsalable.goods.fail': '分页获取滞销数据失败',
  'getting.hac.resource.fail': '获取权限资源失败',
  'finding.urls.fail': '获取用户权限失败',
  'find.user.fail': '查找用户失败',
  'user.login.fail': '用户未登陆',
  'user.not.login': '用户登录过期',
  'user.password.error': '密码错误',
  'user.status.error': '用户被冻结',
  'find.permission.by.nickname.fail': '无登陆权限',
  'find.user.by.nickname.fail': '无登录权限',
};
export default ERRORMESSAGE;
