export const menuMapping = {
  pagingMerchants: {
    order: 1,
    key: 'billing',
    name: '客商主数据',
    url: '/billing',
    parent: 'goodsGrid',
  },
  pagingMdGoods: {
    order: 2,
    key: 'goods',
    name: '商品主数据',
    url: '/goods',
    parent: 'goodsGrid',
  },
  customerRelationship: {
    order: 3,
    key: 'customer',
    name: '客户档案关系',
    url: '/customer',
    parent: 'goodsGrid',
  },
  pagingPssSummary: {
    order: 1,
    key: 'enterSells',
    name: '进销存报表',
    url: '/enterSells',
    parent: 'report',
  },
  pagingSales: {
    order: 1,
    key: 'saledetail',
    name: '销售明细报表',
    url: '/saledetail',
    parent: 'report',
  },
  pagingDeliverys: {
    order: 2,
    key: 'billingDetail',
    name: '提单明细报表',
    url: '/billingDetail',
    parent: 'report',
  },
  pageStockDetail: {
    order: 3,
    key: 'inventory',
    name: '库存明细报表',
    url: '/inventory',
    parent: 'report',
  },
  pagingSalesSummary: {
    order: 4,
    key: 'salereport',
    name: '销售统计报表',
    url: '/salereport',
    parent: 'report',
  },
  pagingDeliverySummary: {
    order: 5,
    key: 'billingCount',
    name: '提单统计报表',
    url: '/billingCount',
    parent: 'report',
  },
  // pagingBlStatistics: {
  //   key: 'billStatistics',
  //   name: '进货统计报表',
  //   url: '/billStatistics',
  //   parent: 'report',
  // },
  pagingStockSummary: {
    order: 6,
    key: 'inventoryStatistics',
    name: '库存统计报表',
    url: '/inventoryStatistics',
    parent: 'report',
  },
  unsale: {
    order: 1,
    key: 'unsale',
    name: '滞销分析',
    url: '/unsale',
    parent: 'analysis',
  },
  paging: {
    order: 2,
    key: 'bestSell',
    name: '畅销分析',
    url: '/bestSell',
    parent: 'analysis',
  },
  dealerPortraitTotal: {
    order: 3,
    key: 'portrayal',
    name: '经销商画像',
    url: '/portrayal',
    parent: 'analysis',
  },
};

export default menuMapping;
